(add-to-list 'load-path "~/.emacs.d/setup")
(server-start)
(require 'sanity)
(require 'compatibility)
(require 'paths)
(require 'keys)

;;(require 'setup-scratch-message)
;;(require 'setup-backup)
;;(require 'setup-elget)
;;(require 'setup-packages)
;;(require 'setup-helpers)
;;(require 'setup-hippie-expand)
;;(require 'setup-mode-line)
;;(require 'setup-auto-revert)
;;(require 'setup-agda)
;; (require 'sublimify)
;; (require 'emacsify)
;; (require 'movelines)
;;(require 'setup-mail)

